# Generated by Django 4.1.7 on 2023-04-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_admissiontest"),
    ]

    operations = [
        migrations.AddField(
            model_name="admissiontest",
            name="start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
